version: "3.8"  

services:
  veritabani:
    image: mysql:5.7
    restart: always
    volumes:
      - verilerim:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wpnet   

  wordpress:
    image: wordpress:latest
    depends_on:
    - veritabani
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: verilerim
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    networks:
      - wpnet 
      
  
volumes:
  verilerim:
  
  
networks:
  wpnet:
    driver: bridge
  